apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: microservice-b-destination-rule
spec:
  host: microservice-b
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: microservice-c-destination-rule
spec:
  host: microservice-c
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2